# frozen_string_literal: true

require "glossarist"
require "json"
require "fileutils"
require "yaml"
require "nokogiri"
require "uri"
require "digest"
require "securerandom"

module CieEilv
  autoload :Version,          "cie_eilv/version"
  autoload :Paths,            "cie_eilv/paths"
  autoload :Uuid,             "cie_eilv/uuid"
  autoload :ApiClient,        "cie_eilv/api_client"
  autoload :TermIndex,        "cie_eilv/term_index"
  autoload :TermEntry,        "cie_eilv/term_entry"
  autoload :TermParser,       "cie_eilv/term_parser"
  autoload :ConceptFile,      "cie_eilv/concept_file"
  autoload :ConceptBuilder,   "cie_eilv/concept_builder"
  autoload :Sections,         "cie_eilv/sections"
  autoload :RegisterBuilder,  "cie_eilv/register_builder"
  autoload :CrossRefLinker,   "cie_eilv/cross_ref_linker"
  autoload :IevMathImporter,  "cie_eilv/iev_math_importer"
  autoload :MathTagConverter, "cie_eilv/math_tag_converter"
  autoload :MathNormalizer,   "cie_eilv/math_normalizer"
  autoload :BibRefMigrator,   "cie_eilv/bib_ref_migrator"
  autoload :SupersedesLinker, "cie_eilv/supersedes_linker"
  autoload :MentionMigrator,  "cie_eilv/mention_migrator"
  autoload :Auditor,          "cie_eilv/auditor"
  autoload :Archive2011,      "cie_eilv/archive_2011"
end
