#!/usr/bin/env ruby
# frozen_string_literal: true

require "cie_eilv"
require "nokogiri"
require "fileutils"

# Scan every cached term page for two things that need manual conversion:
#
# 1. GRAPHICS — `<img>` tags inside the term body. The e-ILV uses these
#    for inline equations, diagrams, and tables-as-images. None of them
#    survive the HTML → YAML transform (TermParser drops them). The
#    upstream ILV publishes them as raster images with no source form,
#    so each needs a human to look at the page and transcribe the
#    formula/diagram into MathML or AsciiDoc stem:[...] notation.
#
# 2. INLINE MATH — italic-letter sequences, subscripts, superscripts,
#    and equals-sign expressions. TermParser preserves these as
#    lightweight HTML (<i>λ</i> etc.). concept-browser renders them
#    as italic text — close, but a variable inside an equals expression
#    should be `stem:[λ = v / ν]` for proper KaTeX rendering.
#
# Output: reference-docs/reports/graphics-and-math.md, a human-readable
# checklist. Concepts with graphics are higher priority (they are
# currently missing data); concepts with inline math are lower priority
# (they render but could be prettier).

OUT_DIR = File.join(CieEilv::Paths::REFERENCE_DOCS, "reports")
OUT_PATH = File.join(OUT_DIR, "graphics-and-math.md")
FileUtils.mkdir_p(OUT_DIR)

graphics = []        # [{termid, src, alt}]
inline_math = []     # [{termid, sample_text}]

Dir.glob("#{CieEilv::Paths::PAGES_DIR}/*.html").sort.each do |path|
  termid = File.basename(path, ".html")
  doc = Nokogiri::HTML(File.read(path))
  body = doc.at_css("article.node--type-eilvterm .field--name-body")
  next unless body

  # Graphics: any <img> that's not a UI icon.
  body.css("img").each do |img|
    src = img["src"].to_s
    alt = img["alt"].to_s.strip
    next if src.match?(/icon|logo|favicon|sprite/i)
    next if src.empty?
    graphics << { termid: termid, src: src, alt: alt }
  end

  # Inline math: paragraphs with sub/sup/I containing math-shaped content.
  body.css("p.Definition, p.Note").each do |p|
    inline = p.css("sub, sup, i")
    next if inline.empty?
    # Heuristic: at least one element with a single math-like char
    next unless inline.any? { |e| e.text.match?(/\A[a-zA-ZλνσφετΓΔπμρΘΩΦΨ]\z/) }

    sample = p.text.strip.gsub(/\s+/, " ").slice(0, 200)
    inline_math << { termid: termid, sample: sample }
    break # one example per concept is enough
  end
end

graphics_by_concept = graphics.group_by { |g| g[:termid] }
inline_math_uniq = inline_math.uniq { |m| m[:termid] }

File.open(OUT_PATH, "w") do |f|
  f.puts "# Graphics + math conversion report"
  f.puts
  f.puts "Generated by `scripts/generate_graphics_report.rb` from the cached"
  f.puts "e-ILV term pages. Each entry below needs manual conversion."
  f.puts
  f.puts "## Concepts with inline graphics (priority: HIGH)"
  f.puts
  f.puts "These concepts have `<img>` tags inside the term body. TermParser"
  f.puts "drops them — they are currently missing from the dataset. Each"
  f.puts "needs a human to:"
  f.puts
  f.puts "1. Open the source URL (https://cie.co.at/eilvterm/<id>)."
  f.puts "2. Transcribe the image's content (formula, diagram, table) into"
  f.puts "   AsciiDoc `stem:[...]` notation or MathML."
  f.puts "3. Edit `datasets/cie-2020/concepts/<id>.yaml` to add the math"
  f.puts "   to the appropriate `definition` or `notes` entry."
  f.puts
  f.puts "Total: **#{graphics_by_concept.length} concepts** with graphics."
  f.puts
  f.puts "| termid | image count | sample alt text |"
  f.puts "|---|---|---|"
  graphics_by_concept.each do |termid, imgs|
    alt_sample = imgs.first[:alt].empty? ? "(no alt)" : imgs.first[:alt].slice(0, 60)
    f.puts "| `#{termid}` | #{imgs.length} | #{alt_sample} |"
  end
  f.puts

  f.puts "## Concepts with inline math (priority: MEDIUM)"
  f.puts
  f.puts "These concepts have inline italic-letter sequences, subscripts, or"
  f.puts "superscripts inside their definition or notes. They render as"
  f.puts "italic text but should use `stem:[...]` for proper KaTeX rendering"
  f.puts "(matches the IALA Dictionary convention)."
  f.puts
  f.puts "Total: **#{inline_math_uniq.length} concepts** with inline math."
  f.puts
  f.puts "First 30 (alphabetical by termid):"
  f.puts
  inline_math_uniq.first(30).each do |m|
    f.puts "- `#{m[:termid]}`: #{m[:sample]}"
  end
  if inline_math_uniq.length > 30
    f.puts
    f.puts "... and #{inline_math_uniq.length - 30} more. See the dataset for the full list."
  end
end

puts "Wrote #{OUT_PATH}"
puts "  Graphics (HIGH priority): #{graphics_by_concept.length} concepts"
puts "  Inline math (MEDIUM priority): #{inline_math_uniq.length} concepts"
